name: hmelnaya_lavka_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_database: ^10.4.5
  firebase_remote_config: ^4.3.12
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_multi_formatter: ^2.12.4
  flutter_rating_bar: ^4.0.1
  nb_utils: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/
